"""
pdf_server.py  —  serves the PDFs in ./documents over HTTP so every machine on the
network can open a cited page.  Run it in a second terminal:

    python pdf_server.py

Same inline / threaded / cached behaviour as before, plus: when
config.PDF_SERVER_REQUIRE_TOKEN is True only links generated by the signed-in app
work, so the documents are not readable by anyone who just knows the address.
"""

import os
import mimetypes
import http.server
import socketserver
import urllib.parse

import config as C

abs_documents_dir = os.path.abspath(C.DOCUMENTS_DIR)
os.makedirs(abs_documents_dir, exist_ok=True)
os.chdir(abs_documents_dir)
mimetypes.add_type("application/pdf", ".pdf")


class InlinePDFHandler(http.server.SimpleHTTPRequestHandler):
    """
    1. Content-Type: application/pdf       — browser renders inline, no download prompt
    2. Content-Disposition: inline         — display, do not save
    3. Cache-Control: public, max-age=3600 — instant on revisit
    4. token check                         — only signed links from the app (optional)
    5. clean terminal                      — only errors are printed
    """

    def _authorised(self) -> bool:
        path = urllib.parse.urlparse(self.path).path
        local_path = self.translate_path(self.path)
        if os.path.isdir(local_path) or not path.lower().endswith(".pdf"):
            self.send_error(404, "Not found")
            return False
        if not (C.AUTH_ENABLED and C.PDF_SERVER_REQUIRE_TOKEN):
            return True
        from auth import verify_pdf_token
        query = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
        if verify_pdf_token(query.get("token", [""])[0]) is None:
            self.send_error(403, "Sign in to the RAG app and open the document from there.")
            return False
        return True

    def do_GET(self):
        if self._authorised():
            super().do_GET()

    def do_HEAD(self):
        if self._authorised():
            super().do_HEAD()

    def list_directory(self, path):
        self.send_error(404, "Not found")
        return None

    def end_headers(self):
        path = self.path.split("?")[0].split("#")[0].lower()
        if path.endswith(".pdf"):
            self.send_header("Content-Type", "application/pdf")
            self.send_header("Content-Disposition", "inline")
        self.send_header("Cache-Control", "public, max-age=3600")
        self.send_header("Access-Control-Allow-Origin", "*")
        super().end_headers()

    def log_message(self, fmt, *args):
        status = args[1] if len(args) > 1 else ""
        if str(status).startswith(("4", "5")):
            super().log_message(fmt, *args)


class ThreadedPDFServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


if __name__ == "__main__":
    server = ThreadedPDFServer((C.PDF_SERVER_HOST, C.PDF_SERVER_PORT), InlinePDFHandler)
    print("=" * 55)
    print("  PDF SERVER  (inline + threaded + cached)")
    print("=" * 55)
    print(f"  Serving from : {abs_documents_dir}")
    print(f"  Host URL     : http://localhost:{C.PDF_SERVER_PORT}")
    print(f"  Network URL  : http://{C.PDF_SERVER_IP}:{C.PDF_SERVER_PORT}")
    print(f"  Token check  : {'ON (links from the app only)' if C.PDF_SERVER_REQUIRE_TOKEN else 'OFF'}")
    print("=" * 55)
    print("  Press Ctrl+C to stop.\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nPDF server stopped.")
        server.shutdown()
